const Orders = [
    {
        productName :'Lexus',
        productNumber :'2003',
        paymentstatus :'Dollar',
        shipping :'SC',
    },
    {
        productName :'Chevrolet',
        productNumber :'2003',
        paymentstatus :'Yuan Renminbi',
        shipping :'Silverado',
    },
    {
        productName :'Oldsmobile',
        productNumber :'1998',
        paymentstatus :'Rial',
        shipping :'LSS',
    },
    {
        productName :'Buick',
        productNumber :'2010',
        paymentstatus :'Ringgit',
        shipping :'LaCrosse',
    },
    {
        productName :'Land Rover',
        productNumber :'2004',
        paymentstatus :'Dinar',
        shipping :'Discovery',
    },
    {
        productName :'Lincoln',
        productNumber :'2001',
        paymentstatus :'Tenge',
        shipping :'Navigator',
    },
    {
        productName :'Mercedes-Benz',
        productNumber :'2008',
        paymentstatus :'Euro',
        shipping :'SLK-Class',
    },
    {
        productName :'BMW',
        productNumber :'2001',
        paymentstatus :'Franc',
        shipping :'5 Series',
    },
    {
        productName :'Dodge',
        productNumber :'1996',
        paymentstatus :'Euro',
        shipping :'Neon',
    },
    {
        productName :'Ford',
        productNumber :'1993',
        paymentstatus :'Rupiah',
        shipping :'Econoline E350',
    },
    {
        productName :'Ford',
        productNumber :'1991',
        paymentstatus :'Euro',
        shipping :'Taurus',
    },
    {
        productName :'Mercedes-Benz',
        productNumber :'2012',
        paymentstatus :'Rupiah',
        shipping :'C-Class',
    },
    {
        productName :'Chevrolet',
        productNumber :'2006',
        paymentstatus :'Yuan Renminbi',
        shipping :'Suburban',
    },
    {
        productName :'Audi',
        productNumber :'1993',
        paymentstatus :'Dinar',
        shipping :'S4',
    },
    {
        productName :'Cadillac',
        productNumber :'2006',
        paymentstatus :'Peso',
        shipping :'STS',
    },
    {
        productName :'Mitsubishi',
        productNumber :'1994',
        paymentstatus :'Ruble',
        shipping :'Mighty Max Macro',
    },
    {
        productName :'Pontiac',
        productNumber :'1978',
        paymentstatus :'Rand',
        shipping :'Grand Prix',
    },
    {
        productName :'Volvo',
        productNumber :'2013',
        paymentstatus :'Rupiah',
        shipping :'S60',
    },
    {
        productName :'Acura',
        productNumber :'2002',
        paymentstatus :'Yuan Renminbi',
        shipping :'MDX',
    },
    {
        productName :'Porsche',
        productNumber :'2007',
        paymentstatus :'Rupiah',
        shipping :'Cayman',
    },
    
]